# @api = http://localhost:4000/api/auth
@api = https://dwfs16-m3s21-ejercicio-auth.onrender.com/api/auth

### sign in
POST {{api}}/login
Content-Type: application/json

{
    "user_name": "DGOMEZ",
    "password": "121212"
}

### sign in
POST {{api}}/register
Content-Type: application/json

{
    "user_name": "DGOMEZ",
    "password": "121212"
}

### renovar token
{{api}}/renew
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YTMyZTRhN2VmMmQwNjdmNjZlMDNhMSIsImlhdCI6MTY4OTYyNTA1OSwiZXhwIjoxNjg5NjM5NDU5fQ.3zfXTBWRSmOgM1jB0GI09mYHoQO7y5wXKuFxQle1cD0